sudo: enabled
dist: xenial
language: python
python:
  - 3.6
  - 3.7

before_install:
  # Use the pre-installed nvm version to update node
  # Apparently Travis comes with nvm even on the python containers
  - nvm install v12.18.1
  - nvm use v12.18.1
  - node -v
  - npm version

install:
  # Install package, while updating dependencies
  - pip install --upgrade --upgrade-strategy eager .[dev]

script:
  # Run all pytest unit tests
  - cd tests && python -m pytest -v . --cov readabilipy --cov-report term-missing --benchmark-disable && cd ..
  # Run pyflakes for error detection
  - pyflakes *.py readabilipy tests
  # Check PEP8 compliance (ignoring long lines)
  - pycodestyle --statistics --ignore=E501 --count *.py readabilipy tests
  # Run pylint for stricter error checking
  - pylint readabilipy ./tests

after_success:
  # Upload results to coveralls.io
  - coveralls
