sudo: enabled
dist: xenial
language: python
python: 3.6

before_install:
  # Install node.js following instructions from
  #   https://nodejs.org/en/download/package-manager/
  - sudo apt install curl
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
  - sudo apt install nodejs

install:
  # Install node.js dependencies
  - npm install
  # Install python dependencies
  - pip install -r requirements-dev.txt

script:
  # Run all pytest unit tests
  - python -m pytest -v tests
  # Run pyflakes for error detection
  - pyflakes .
